src/bond/james.clj, test/bond/test/james.clj
Basically just a (with-redefs foo (bond/spy bar) ... ) but a little tidier.
Useful when unit-testing integration points, where the function needs to return a value for the code being tested to continue, calling the function is undesirable because of side-effects, but validating the function was called correctly is still a useful test.
=> Allow replacements to be specified in with-stub.

README.md, circle.yml, project.clj, requirements.txt, test/bond/test/james.clj
- Specify the version of Java that should be used for testing
- Upgrade Clojure dep to 1.7
- Add cloverage for code coverage data
- Add test result XML output
=> Improve the build setup - add code coverage test reports

src/bond/james.cljc
`Exception` is not valid cljs, but `js/Error` is. added a conditional to catch the correct exception in the correct enviornment
=> fixed a cljs compilation error

README.md
Right now it is not clear from the documentation that you can specify a replacement function for `with-stub`. There is a comment about this functionality in the code [here](https://github.com/circleci/bond/blob/master/src/bond/james.cljc#L37), so adding it to the README as well.
=> Add an example for using `with-stub` with a replacement function

README.md, src/bond/james.cljc, test/bond/test/james.cljc
Sometimes we need to stub with different return value/exception for the same method call. Typical use case could be mocking iterators. Another use case that I faced is testing retries. 
For example, we are testing a function which makes a network call and on exception, retries once. For testing, we need to mock the network call with two possible outcomes: first it should throw an exception, next time, it should return expected result.
=> Add support for stubbing consecutive calls.

circle.yml, project.clj
so we don't have to manually publish new revs of this library to clojars.
=> added auto-deployment to clojars at version 0.2.build-num

project.clj
we need this this to enable automatic deployment to clojars.
=> added lein-version-spec

README.md, project.clj, src/bond/james.cljc, test/bond/test/james.cljc
Add `with-spy-namespaces` and `with-stub-namespaces` which will spy/stub every function in the namespaces passed to them. This can be useful for establishing boundaries in tests.
=> Allow spying and stubbing entire namespaces.

README.md, project.clj, src/bond/james.cljc, test/bond/test/james.cljc, test/bond/test/target.cljc
They couldn't stub/spy across namespaces because the previous implementation didn't fully qualify the redef'ed symbols.
=> Fix with-spy-ns and with-stub-ns

README.md, src/bond/james.cljc, test/bond/test/james.cljc, test/bond/test/target.cljc
Some people have a problem using bond for private functions because of pretty cryptic syntax, this PR adds a bit better support.
Before private fn stubbing/checking looked like:
```clojure
(deftest foo-is-called
+  (with-stub! [[foo/foo (fn [x] "foo")]]
+    (is (= "foo" (#'foo/foo 1)))
+    (is (= [1] (-> @#'foo/foo bond/calls first :args)))))
```
Notice the difference in calling private function and checking stub args. Now it'll be possible to have the same (`#'foo/foo`) syntax for both.
=> Better support for stubbing private fns

project.clj
Bond only needs Clojure and CLJS dependencies for its own build/tests.
Any consumer of bond will already have a Clojure or CLJS dependency,
don't force them to exclude dependencies from bond itself.
=> Drop runtime dependencies

src/bond/james.cljc, test/bond/test/james.cljc, test/bond/test/target.cljc
If a function was generated without `:arglists` metadata then it can't be stubbed using `with-stub!` since `stub!` can't verify the arity of the replacement function.
Instead of giving an inscrutable error message, we now assert that `:arglists` exists and produce an error message which points the user in the right direction.
Fixes: #41
=> Useful error message for when stub!/with-stub! will fail

project.clj
Differences from 0.3.1 -> 0.3.2:
- `with-stub!` now produces more useful errors when attempting to stub function with no `:arglists` in their metadata. (#43)
- Updates to the README (#40, #42)
=> Bump version to 0.3.2

README.md, project.clj
I will `tag 0.4.0` and release to clojars when merged.
=> bump 0.4.0

project.clj
So that we test against a more recent and representative version of
Clojure and no longer need to pin an older version of Cloverage for
compatibility with it.
Depends (and is based on) https://github.com/circleci/bond/pull/53
=> Upgrade Clojure and Cloverage versions

.circleci/config.yml, CHANGELOG.md, README.md, project.clj
So that we don't need to find credentials and remember how to release
changes manually. Git tags are used to trigger publishing so that we
don't re-publish over existing versions every time we merge to master.
It also means that we're more likely to remember to tag and don't need
to add any logic or credentials for the workflow to create tags.
An alternative would have been to use the build number as a patch
version, but it's unwieldy for both for users and for us to maintain the
versions in `README.md` and `CHANGELOG.md`.
The `CLOJARS_USERNAME` and `CLOJARS_TOKEN` environment variables have
been added to the project. At the moment they belong to an individual
but we'll move them to a machine user later. The project already has
"build forks" and "pass secrets to fork builds" disabled, …
=> Release version 0.5.0 with automation

.circleci/config.yml
In order to allow `publish` to run on a tag. Previously the tag I pushed
resulted in "no workflow" because of: (https://circleci.com/docs/2.0/configuration-reference/#tags)
> Additionally, if a job requires any other jobs (directly or indirectly), you must specify tag filters for those jobs.
I've deleted the `0.5.0` tag that I previously created and will recreate
it after this change. This isn't great form, as tags should be
immutable, but it won't have been used for anything yet and doesn't
warrant bumping the version because we failed to release it.
=> ci: Add tag filter to test

.circleci/config.yml
`*coverage*.*` pattern is scooped in the default setup
cf https://github.com/codecov/codecov-bash/blob/ce0eb066b997622ff071255e8aa4c239099c17fc/codecov#L1297
=> don't specify codecov file parameter

.circleci/config.yml
Committed via https://github.com/asottile/all-repos
=> [SRE-3660] Update the Codecov orb to 1.2.2

CHANGELOG.md, README.md, project.clj, src/bond/assertions.clj, test/bond/assertions_test.clj
On insights we noticed that the assertions available were often not flexible enough for us, and `called-with-args` is confusing without inspecting the source, and not useful on functions that are called many times through the course of a test (`tracing/` methods, for example).
This adds `called-once-with-args` which we've written and use on Insights. We recognize that the same effect can be achieved with `called-with-args` and only providing the set of args we expect, but we've found the name and behaviour of the function confusing.
This also adds `called-at-least-once-with-args?` which is what we had expected `called-with-args` to be. This checks that the `f` provided was called with the provided arguments at least once.
I'd like to propose changing the `called-with-args` doc string to …
=> Add called-once-with-args? and called-at-least-once-with-args? to bond/assertions

README.md
=> Fix typo describing `with-spy` in README
